### ISSUE TITLE
Send Notification to some users by ID

### ISSUE THREAD

**Issue by AEK-BKF** [MatviiB/notifier#1]
Hi,
Thank you so much for this nice package :)
Please, is there any way to send notification to users by ID ?
Something like this :
`event(new Notify($users, $data, '/chart'));`

Thanks :)

**Comment by MatviiB** [comment]
yes, for now this is in my mind

**Comment by MatviiB** [comment]
Released in v1.2.0 ! 
`event(new Notify($data, $routes, $users));`
