### ISSUE TITLE
Popup notify example

### ISSUE THREAD

**Issue by marioene** [MatviiB/notifier#14]
Excellent package. I was able to start your chart example.

But, can you provide a full example with a popup notify message?

Have I to create a command console for this also, like for chart?

**Comment by MatviiB** [comment]
Hi
first you need `@include('connect_and_show')`
and then something like this in test command
```
    $types = ['warn', 'success', 'error', 'info'];

        while (true) {
            $value = random_int(10, 100);

            if (rand(0, 4) > 0) {
// send value for chart
                $data = [
                    'value' => $value
                ];
            } else {
// send value for popup
                $data = [
                    'note' => 1,
                    'type' => $types[array_rand(['warn', 'success', 'error', 'info'])],
                    'text' => 'Random str: ' . str_random(16),
                ];
            }

            event(new Notify($data, ['notifier']));
            usleep(rand(100000, 300000));
        }
```

**Comment by MatviiB** [comment]
so main thing is send $data['note' => 1, 'text' => 'asdf']
note parameter will fire to use popup

and include connect_and_show layout of course

**Comment by marioene** [comment]
Ok. I understand the code in the Command Console. But the the code in view how must be?

After `include('connect_and_show')`...

**Comment by MatviiB** [comment]
You close issue, so do you still have question or no?

**Comment by marioene** [comment]
Your solution works very well. I have no further questions.
