### ISSUE TITLE
HTML component with live text

### ISSUE THREAD

**Issue by marioene** [MatviiB/notifier#15]
Can you extend your package to provide live information to a html component  with text (label, input text ...) in a view?

It's very useful when you want to display  weather info, status of a server in real-time, a live parameter ...

**Comment by MatviiB** [comment]
you don't need extend package for this. everything you need is 
```
socket.addEventListener('message', function (event) {
            var data = JSON.parse(event.data).data;
            document.getElementById("demo").innerHTML = data.html;
        });
```

you can send any data. how this data will execute on the client is a your choice

**Comment by marioene** [comment]
Great! It's working.
