### ISSUE TITLE
Disable receiving data with "message" key and "test" value

### ISSUE THREAD

**Issue by marioene** [MatviiB/notifier#16]
How to disable receiving data with `message` and `test` value?

In console log I see this:

`Message from server: {"data":{"message":"test"}}`

and this disrupts my personalized data sender, I have to put in this case conditions with:

`
if (data['message'] != 'test') {
  if (data['jdrac_temperature'] != null) {
    document.getElementById("jdrac_temperature").innerHTML = data['jdrac_temperature'];
  }
}
`

**Comment by MatviiB** [comment]
maybe just stop send data with message : test ?

**Comment by marioene** [comment]
In my code I have nothing send with message : test.

**Comment by MatviiB** [comment]
yes, you have for sure. check console commands
