### ISSUE TITLE
Usage issues !

### ISSUE THREAD

**Issue by AEK-BKF** [MatviiB/notifier#3]
Please, provide a sample tutorial to show how do we use it.
I found these issues when following your read-me.

`event(new Notify($data));`

> Class 'App\Http\Controllers\Notify' not found

On front-end :
```
<script>
    socket.addEventListener('message', function (event) {
        console.log('Message from server', event.data);
    });
</script>
```

> ReferenceError: socket is not defined

**Comment by MatviiB** [comment]
OK. 
after installation add to config - 
```
'urls' => [
        '/',
        '/chart'
    ]
```
to web.php
```
Route::get('chart', function () {
    return view('chart');
});
```
create view `/resources/views/chart.blade.php`

```
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Chart</title>
</head>
<body>
<canvas id="myChart"></canvas>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script type="text/javascript">

    var data = [12, 19, 3, 17, 6, 3, 7, 45, 60, 25];

    var myChart = new Chart(document.getElementById('myChart'), {
        type: 'line',
        data: {
            labels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            datasets: [{
                label: 'example',
                data: data
            }]
        }
    });

    socket.addEventListener('message', function (event) {
        myChart.data.datasets[0].data.splice(0, 1);
        myChart.data.datasets[0].data.push(JSON.parse(event.data).data.value);
        myChart.update();
    });
</script>
</body>
</html>
```
In .env fix your APP_URL `APP_URL=http://<<U APP URL>>`
Create test command `php artisan make:command Test`
```
use MatviiB\Notifier\Events\Notify; 

...

protected $signature = 'test';

public function handle()
    {
        $i = 0;

        while ($i < 100) {
            $value = random_int(10, 100);
            $data['value'] = $value;
            event(new Notify($data, '/chart'));
            usleep(rand(100000, 500000));
        }
}
```
Run: `php artisan notifier:init`
Run in another shell:  `php artisan test`
Open `/chart` page.

**Comment by AEK-BKF** [comment]
Thank you so much for quick answer !
I tried this :

In app blade :
```
 <script>
        socket.addEventListener('message', function (event) {
            console.log('Message from server', event.data);
        });
    </script>
```

In controller :
```
use MatviiB\Notifier\Events\Notify;
...
event(new Notify('Hello World!', '/test'));
```

I run :
`php artisan notifier:init`

But I still get this error in browser console :

> ReferenceError: socket is not defined

**Comment by MatviiB** [comment]
did you add `/test` to config->urls?

**Comment by MatviiB** [comment]
i added tutorial (example) to readme file

**Comment by AEK-BKF** [comment]
Yes ! and also I tried with no url :
event(new Notify('Hello World!'));
It should send to all urls right ?
Or should I add socket.io js ?

**Comment by MatviiB** [comment]
check your application host name and  .env->APP_URL. this must be the same

**Comment by AEK-BKF** [comment]
I'm on local dev :
I set :` http://127.0.0.1`
if I set `http://127.0.0.1:8000`  it shows me an error when I run 
 php artisan notifier:init 
`stream_socket_server("tcp://127.0.0.1:8000:3000", "Address already in use")`

**Comment by MatviiB** [comment]
it means your local port 3000 is already in use. with this or another feature. 
try to use named application. i tested on `dev.clean` for example. i didn't test on 127.0.0.1 actually.
and use 1.0.1 version. thanks

**Comment by AEK-BKF** [comment]
Nope it's  not used ! I check `netstat -ntlp | grep LISTEN` .
the error said :` "tcp://127.0.0.1:8000:3000", "Address already in use"`
we can't reach url with double ports ! 
I set the URL correctly ! just `http://127.0.0.1`
NB: where did you define socket variable here ?:
 ```
<script>
        socket.addEventListener('message', function (event) {
            console.log('Message from server', event.data);
        });
    </script>

```

**Comment by AEK-BKF** [comment]
Waw ! I fixed the problem ! I set URL : `http://localhost` instead of `http://127.0.0.1`
I works fine now ! but one matter again ^^ :
If I don't set URL, like this :` event(new Notify('Hello World!'));`
it doen't work ! I can't get message in all URL

**Comment by MatviiB** [comment]
You should add page url to config and add something like this to view: 
```
<script type="text/javascript">
            socket.addEventListener('message', function (event) {
                console.log(event.data)
            });
        </script>
```
if page isn't in config package will not load to application.

**Comment by AEK-BKF** [comment]
Never mind I understood ! it sends to every url defined in config notifier !
But it works just for simple URL `/xx `  `/yy`  `/zz `...
what about` /xx/{id}`    `/yy/{id1}/show/{id2} `... ?

**Comment by MatviiB** [comment]
this will be develop in the feature :smile:

**Comment by MatviiB** [comment]
Thanks for your attention)

**Comment by AEK-BKF** [comment]
Really it's a very good package !! 
If I have time I'll help you to improve it as well !
Please we're waiting for that feature and also for sending to some users id ^^'
GooooooD Luuuuuck  :grinning:
