### ISSUE TITLE
Suggestion: Send to predefined users ID

### ISSUE THREAD

**Issue by AEK-BKF** [MatviiB/notifier#4]
I can send to predefined users ID by this way :
```
$userID = [1,2,3];
$data = ['id' => $userID, 'title' => 'Info :)', 'content' => 'Hi there !'];
event(new Notify($data));
```
And in the main blade :

```
<script>        
        socket.addEventListener('message', function (event) {
            if(JSON.parse(event.data).data.id.includes({!! Auth::id() !!}))
            {
                toastr.info(JSON.parse(event.data).data.content, JSON.parse(event.data).data.title);
            }
        });
</script>
```
So you may update it to get it works like this :
`event(new Notify($usersID, $data));`

Good Luck :grinning:

**Comment by MatviiB** [comment]
Yes, BUT if i change N in `data.id.includes(N)` i can see not mine data

**Comment by AEK-BKF** [comment]
No! you should not change  it there, but you can change in $suersID 
here : `$userID = [1,2,3];`
It works fine for me, just create two users, and set one userID. you'll receive notification for just this one.

**Comment by MatviiB** [comment]
i mean this is vulnerability

**Comment by AEK-BKF** [comment]
Ok I updated it :
in app.js :

```
socket.addEventListener('message', function (event) {
        if(JSON.parse(event.data).data.id.includes(window.Laravel.userID))
        {
            toastr.info(JSON.parse(event.data).data.content, JSON.parse(event.data).data.title);
        }
    });
```
In main blade: 
 ```
<script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
            'userID' =>  auth()->id()
        ]) !!};        
    </script>
```
Of course you should install node & npm and then run : `npm run dev`

May this helps ^^'

**Comment by MatviiB** [comment]
i don't understand :grinning: 
it still vulnerability.
should "think" a way without any `id` on client side logic

**Comment by AEK-BKF** [comment]
No ! it's Laravel way to use Vue.js ! 
this code :
```
socket.addEventListener('message', function (event) {
        if(JSON.parse(event.data).data.id.includes(window.Laravel.userID))
        {
            toastr.info(JSON.parse(event.data).data.content, JSON.parse(event.data).data.title);
        }
    });
```
doesn't appear in client side !

**Comment by AEK-BKF** [comment]
Otherwise we're waiting for you to get a solution for this and also to send notifier to all urls ^^'

**Comment by MatviiB** [comment]
Hi. you can review last release.
now you need to add `@include('notifier::connect')` to your main layout to use it on all pages.
and without this including client will not connect to socked server at all, i removed auto connection.
