### ISSUE TITLE
Error Supervisor to run notifier:init 

### ISSUE THREAD

**Issue by AEK-BKF** [MatviiB/notifier#5]
Hi again and sorry for my issues ^^
I'm trying to configure my supervisor but it fails !

`error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228`

**Comment by MatviiB** [comment]
this is totally your local issue ) sorry

**Comment by AEK-BKF** [comment]
You're right ! I didn't start supervisor ! :D
