### ISSUE TITLE
 Initialize the connection on all pages of the admin panel.

### ISSUE THREAD

**Issue by DmitrySkibitsky** [MatviiB/notifier#7]
essence: creating a connection on all routs (config/notifier.php > urls).
That there was such possibility if it is necessary to send the notification on a template which is connected on main layout.

**Comment by MatviiB** [comment]
What?)

**Comment by MatviiB** [comment]
You need to implement this on all pages?

**Comment by MatviiB** [comment]
This will be released in the nearest feature

**Comment by DmitrySkibitsky** [comment]
@MatviiB Прости. Я не видел что ты Украинец) Суть в том что есть шаблон на который планировалось отправляться сообщения. А тот шаблон подключен на всех страницах. И поэтому непонятно как в таком случае поступать.

**Comment by DmitrySkibitsky** [comment]
Но я решил уже сделать это все на отдельной странице и только под нее соединение выдавать.

**Comment by MatviiB** [comment]
Скажу більше. Я з Черкас) я вже пишу оновлення. в наступній версії буде підключатися трохи по іншому. а зараз, так, треба всі урли прописати в конфігах. але якщо там складений урл, який містить `/post/{post_id}/comment/{comment_id}`, то рішення по суті немає. Але я вже працюю над цим.

**Comment by DmitrySkibitsky** [comment]
@MatviiB , вот оно как) Наши люди) Приятно приятно)) Но роутов то в админке много) Это придется все переписать + поддерживать в актуальном состоянии все время. Лучше уже поискать решение.)

**Comment by AEK-BKF** [comment]
English please to understand your issue !

**Comment by DmitrySkibitsky** [comment]
@AEK-BKF , essence: creating a connection on all routs (config/notifier.php > urls). 
That there was such possibility if it is necessary to send the notification on a template which is connected on main layout.

**Comment by MatviiB** [comment]
Guys, I need few days to finished this. Actually few nights))
